### ISSUE TITLE
Raised exception has changed when a storage object is not found: RTSLibNotInCFS became RTSLibError

### ISSUE THREAD

**Issue by cvubrugier** [agrover/rtslib-fb#57]
After upgrading rtslib-fb in a NAS firmware at work that uses a custom software on top of rtslib-fb, I observed that the exception raised when a storage object is not found in lookup mode is now RTSLibError. It used to be RTSLibNotInCFS prior to rtslib-fb v2.1.fb44:

Behaviour up to rtslib-fb v2.1.fb43:

    >>> import rtslib
    >>> rtslib.tcm.FileIOStorageObject('foo', None, None, None, False)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "build/bdist.linux-x86_64/egg/rtslib/tcm.py", line 566, in __init__
      File "build/bdist.linux-x86_64/egg/rtslib/tcm.py", line 48, in __init__
      File "build/bdist.linux-x86_64/egg/rtslib/tcm.py", line 798, in __init__
      File "build/bdist.linux-x86_64/egg/rtslib/node.py", line 53, in _create_in_cfs_ine
    rtslib.utils.RTSLibNotInCFS: No such _Backstore in configfs: /sys/kernel/config/target/core/fileio_0.

Since rtslib-fb v2.1.fb44:

    >>> import rtslib_fb
    >>> rtslib_fb.tcm.FileIOStorageObject('foo', None, None, None, False)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "build/bdist.linux-x86_64/egg/rtslib/tcm.py", line 566, in __init__
      File "build/bdist.linux-x86_64/egg/rtslib/tcm.py", line 48, in __init__
      File "build/bdist.linux-x86_64/egg/rtslib/tcm.py", line 785, in __init__
    rtslib.utils.RTSLibError: Storage object fileio/foo not found

@grover, I can provide a patch if you consider this is an issue.

**Comment by agrover** [comment]
@cvubrugier can we close this? I think so?

**Comment by cvubrugier** [comment]
> @cvubrugier can we close this? I think so?

Yes!
